Adds support for mock $extensions
alan-cooney/appsync-template-tester pull request #28
Opened 2023-01-27 02:41 UTC by danwhitfield

Could support be added to this project for mocking the methods available via $extension? I am wanting to assert that $extensions.evictFromApiCache is invoked in my VTL template with the correct arguments.

2023-01-31 00:12 UTC, danwhitfield commented
Hey @alan-cooney, any chance we could get this merged in this week, please? Thanks :)

2023-02-05 08:37 UTC, alan-cooney requested changes
Thanks for submitting this - just a few small suggested changes to make the comments/test name a little clearer.

If you're happy to approve these I can merge in

2023-02-05 08:37 UTC, alan-cooney commented on src/tests/index.test.ts
> +test("resolve with additional extensions", () => {
```suggestion
test("mocked extension is called", () => {
```

2023-02-05 08:37 UTC, alan-cooney commented on src/tests/index.test.ts
> +  // Given.
```suggestion
  // Create the parser with the mock extension function
```

2023-02-05 08:37 UTC, alan-cooney commented on src/tests/index.test.ts
> +  // When.
```suggestion
```

2023-02-05 08:37 UTC, alan-cooney commented on src/tests/index.test.ts
> +  // Then.
```suggestion
```

2023-02-05 08:37 UTC, alan-cooney commented on README.md
> +  // Given.
```suggestion
  // Create the parser with the mock extension function
```

2023-02-05 08:37 UTC, alan-cooney commented on README.md
> +  // When.
```suggestion
```

2023-02-05 08:37 UTC, alan-cooney commented on README.md
> +  // Then.
```suggestion
```

2023-02-05 18:17 UTC, danwhitfield commented
Hi @alan-cooney, I have committed all the changes you suggested. Thanks

2023-02-05 18:18 UTC, alan-cooney approved these changes

2023-02-05 18:18 UTC, merged

2023-02-05 18:18 UTC, alan-cooney commented
Thanks for the PR! The CD will automatically push this up to the npmjs package in a few minutes